language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - export CARGO_TARGET_DIR=`pwd`/target
  - cargo build --verbose
  - cargo test --verbose
  - rustdoc --test README.md -L target/debug -L target/debug/deps
  - cargo doc --no-deps
  - cargo doc --no-deps --manifest-path=bzip2-sys/Cargo.toml
after_success:
  - travis-cargo --only nightly doc-upload
notifications:
  email:
    on_success: never
env:
  global:
    secure: LnMCySc8+eTOXugkmPTLwZTT2pgrhxY3wiEuQ2eBaMcSwzZswDLNFBhjI0WWF6MPl9Ou9BSUbBtwwxKztY8jhtIDRSxn/CisWMFb4mRM1T/eq9LTDU+Po/WQ4zZP6ZUYpch8UgrcsiRF/VasvhcyNQrUGI16eMCky5NeqaBwaJU=
