language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

    - name: "master doc to gh-pages"
      rust: nightly
      script:
        - cargo doc --no-deps
        - cargo doc --no-deps --manifest-path=bzip2-sys/Cargo.toml
        - curl -O https://raw.githubusercontent.com/alexcrichton/rust-travis-deploy/master/travis-deploy.rs
        - rustc travis-deploy.rs
        - (cd target/doc && ../../travis-deploy)

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose --features tokio
  - rustdoc --test README.md -L target/debug -L target/debug/deps

notifications:
  email:
    on_success: never
