[package]

name = "bzip2"
version = "0.0.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["bzip", "encoding"]
repository = "https://github.com/alexcrichton/bzip2-rs"
homepage = "https://github.com/alexcrichton/bzip2-rs"
documentation = "http://alexcrichton.com/bzip2-rs"
description = """
Bindings to libbzip2 for bzip2 compression and decompression exposed as
Reader/Writer streams.
"""

[dependencies.bzip2-sys]
version = "*"
path = "bzip2-sys"
